# Generated by Django 4.1.4 on 2022-12-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
